### ISSUE TITLE
Street names are missing or not visible if you bring in aerial imagery

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-RecreationViewer#54]

**Comment by nfunicello** [comment]
Here's an Imagery with Labels basemap option. 
http://www.arcgis.com/home/item.html?id=716b600dbbac433faa4bec9220c76b3a
Just disable place names and political boundaries because they conflict with the boundaries we have in the viewer. 

Or there's a World Transportation service that can be added to the aerial we already have
http://www.arcgis.com/home/item.html?id=94f838a535334cf1aa061846514b77c7

**Comment by Jfairfield1** [comment]
I added the world transportation layer to the map when the satellite imagery is toggled.
